spring.profiles.active: dev

server.port: 8080

spring:
  application:
    name: spring-boot-tasks-manager
  datasource:
    driver-class-name: ${ENV_DRIVER_CLASS_NAME}
    url: ${ENV_DATASOURCE_URL}
    username: ${ENV_DATASOURCE_SERVICE_USERNAME}
    password: ${ENV_DATASOURCE_SERVICE_PASSWORD}
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.lob.non_contextual_creation: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


ENV_DATASOURCE_URL: jdbc:postgresql://localhost:5432/app_db
ENV_DATASOURCE_SERVICE_USERNAME: postgres
ENV_DATASOURCE_SERVICE_PASSWORD: password
ENV_DRIVER_CLASS_NAME: org.postgresql.Driver