CREATE TABLE if NOT EXISTS users
(
    user_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name   VARCHAR NOT NULL,
    middle_name VARCHAR,
    last_name   VARCHAR NOT NULL,
    email       VARCHAR UNIQUE,
    password    VARCHAR NOT NULL
);


CREATE TABLE if NOT EXISTS boxes
(
    box_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    box_name    VARCHAR NOT NULL,
    start_time  TIME    NOT NULL,
    end_time    TIME    NOT NULL,
    time_factor FLOAT   NOT NULL
);


CREATE TABLE if NOT EXISTS service_type
(
    service_type_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_name    VARCHAR NOT NULL,
    duration        TIME    NOT NULL,
    price           BIGINT  NOT NULL
);


CREATE TABLE if NOT EXISTS order_status
(
    status_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_name VARCHAR UNIQUE NOT NULL
);


CREATE TABLE if NOT EXISTS orders
(
    order_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date     TIMESTAMP NOT NULL,
    time     TIME      NOT NULL
);


CREATE TABLE roles
(
    role_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR UNIQUE NOT NULL
);


CREATE TABLE discounts
(
    discount_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    min_discount INTEGER DEFAULT (0),
    max_discount INTEGER DEFAULT (0)
)