ALTER TABLE IF EXISTS orders
    ADD total_price FLOAT;


CREATE TABLE IF not exists password_resets
(
    reset_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expire_at    TIMESTAMP NOT NULL,
    token        VARCHAR,
    new_password VARCHAR,
    id_of_user   INTEGER,
    CONSTRAINT fk_user
        FOREIGN KEY (id_of_user)
            REFERENCES users (user_id)
)